//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCenterLib.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableCouresView
    {
        public int AvailableCourseID { get; set; }
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Requirement_CourseID { get; set; }
        public bool IsProgramming { get; set; }
        public bool IsGroupDays1 { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int InstructorID { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string LastName { get; set; }
    }
}
