//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCenterLib.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableCours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AvailableCours()
        {
            this.WaitingLists = new HashSet<WaitingList>();
            this.ActiveCourseByGroups = new HashSet<ActiveCourseByGroup>();
        }
    
        public int AvailableCourseID { get; set; }
        public int CourseID { get; set; }
        public int InstructorAvailabilityID { get; set; }
        public Nullable<System.DateTime> StartAt { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual InstructorAvailability InstructorAvailability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaitingList> WaitingLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActiveCourseByGroup> ActiveCourseByGroups { get; set; }
    }
}
