//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCenterLib.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructorAvailability
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstructorAvailability()
        {
            this.AvailableCourses = new HashSet<AvailableCours>();
        }
    
        public int InstructorAvailabilityID { get; set; }
        public int InstructorID { get; set; }
        public int timeSlotID { get; set; }
        public bool IsGroupDays1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailableCours> AvailableCourses { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
    }
}
