//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCenterLib.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSlot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeSlot()
        {
            this.InstructorAvailabilities = new HashSet<InstructorAvailability>();
        }
    
        public int TimeSlotID { get; set; }
<<<<<<< Updated upstream
        public System.TimeSpan StartTime { get; set; }
=======

        [Display(Name = "Start Time")]
        //[DataType(DataType.Date)]
        public System.TimeSpan StartTime { get; set; }

        [Display(Name = "End Time")]
        //[DataType(DataType.Date)]
>>>>>>> Stashed changes
        public System.TimeSpan EndTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructorAvailability> InstructorAvailabilities { get; set; }
    }
}
