//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCenterLib.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainingCenterLibDbContext : DbContext
    {
        public TrainingCenterLibDbContext()
            : base("name=TrainingCenterLibDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<ActionType> ActionTypes { get; set; }
        public virtual DbSet<AuditTrail> AuditTrails { get; set; }
        public virtual DbSet<AvailableCours> AvailableCourses { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<InstructorAvailability> InstructorAvailabilities { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<MasterEntity> MasterEntities { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RunningCours> RunningCourses { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TimeSlot> TimeSlots { get; set; }
        public virtual DbSet<WaitingList> WaitingLists { get; set; }
        public virtual DbSet<AuditTrailView> AuditTrailViews { get; set; }
        public virtual DbSet<AvailableCouresView> AvailableCouresViews { get; set; }
        public virtual DbSet<InstructorsAvailabilityView> InstructorsAvailabilityViews { get; set; }
        public virtual DbSet<WaitingListView> WaitingListViews { get; set; }
    }
}
