//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCenterLib.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaitingList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WaitingList()
        {
            this.RunningCourses = new HashSet<RunningCours>();
        }
    
        public int WaitingListID { get; set; }
        public int StudentID { get; set; }
        public int AvailableCourseID { get; set; }
        public string GroupName { get; set; }
        public bool IsPaid { get; set; }
        public bool IsCash { get; set; }
    
        public virtual AvailableCours AvailableCours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RunningCours> RunningCourses { get; set; }
        public virtual Student Student { get; set; }
    }
}
