//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCenterUI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrailView
    {
        public int AuditTrailID { get; set; }
        public int ActionTypeID { get; set; }
        public string ActionTypeName { get; set; }
        public string DisplayName { get; set; }
        public int ActionID { get; set; }
        public string ActionName { get; set; }
        public string ActionsInfo { get; set; }
        public System.DateTime TransactionTime { get; set; }
        public int EntityID { get; set; }
        public string EntityName { get; set; }
        public string EntityInfo { get; set; }
        public string EntityRecord { get; set; }
    }
}
