//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCenterUI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaitingListView
    {
        public int WaitingListID { get; set; }
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int AvailableCourseID { get; set; }
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Requirement_CourseID { get; set; }
        public bool IsProgramming { get; set; }
        public int InstructorAvailabilityID { get; set; }
        public int InstructorID { get; set; }
        public string InstructorName { get; set; }
        public string GroupName { get; set; }
        public string InstructorEmail { get; set; }
        public string InstructorPhone { get; set; }
        public int timeSlotID { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public bool IsGroupDays1 { get; set; }
    }
}
